spring:
  application:
    name: lab1
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:9000/realms/devrealm
          jwk-set-uri: http://localhost:9000/realms/devrealm/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lab1
    username: mitrian
    password: mitrian
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

